import React from "react"
import "@/app/globals.css"
import { Providers } from "@/components/providers"
import { Inter } from "next/font/google"
import type { Metadata } from "next"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Utkarsh Deoli | Developer",
  description: "Portfolio of Utkarsh Deoli, a Developer specializing in modern web technologies, AI, Mobile Application Development and DevOps.",
  keywords: [
    "Utkarsh Deoli",
    "Full Stack Developer",
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Web Developer",
    "Frontend Developer",
    "Backend Developer",
    "Portfolio",
    "Software Engineer",
    "Web Development",
    "Web Design",
    "UI/UX Designer",
    "Software Development",
    "Programming",
    "Tech Enthusiast",
    "Open Source Contributor",
    "Tech Blogger",
    "Tech Portfolio",
    "Web Applications",
    "Responsive Design",
    "Modern Web Technologies",
    "Frontend Frameworks",
    "Backend Frameworks",
    "APIs",
    "Database Management",
    "Cloud Computing",
    "DevOps",
    "Agile Development",
    "Software Architecture",
    "Version Control",
    "Git",
    "Software Testing",
    "Continuous Integration",
    "Continuous Deployment",
    "User Interface",
    "User Experience",
    "Web Accessibility",
    "Cross-Browser Compatibility",
    "Performance Optimization",
    "Progressive Web Apps",
    "Mobile-First Design",
    "Single Page Applications",
    "Component-Based Architecture",
    "State Management",
    "JavaScript Frameworks",
    "TypeScript Development",
    "React Development",
    "Next.js Development",
    "Node.js Development",
    "Full Stack JavaScript",
    "Software Solutions",
    "Tech Innovations",
    "Web Technologies",
    "Software Projects",
    "Tech Portfolio Website",
    "Personal Portfolio",
    "Professional Portfolio",
    "AI and Machine Learning",
    "Blockchain Technology",
    "Internet of Things",
    "Cybersecurity",
    "Data Science",
    "Cloud Services",
    "MLops",
    "AI Development",
    "Large Language Models",
    "AI Applications",
    "AI Portfolio",
    "AI Projects",
    "AI Solutions",
    "AI Technologies",
    "AI in Web Development",
    "AI in Software Development",
    "AI in Full Stack Development",
    "AI in Web Applications",
    "AI in User Experience",
    "AI in Web Design",
    "AI in Software Engineering",
    "AI in Programming",
    "AI in Tech",
    "AI in Software Solutions",
    "AI in Tech Innovations",
    "AI in Modern Web Technologies",
    "AI in Frontend Development",
    "AI in Backend Development",
    "AI in APIs",
    "AI in Database Management",
    "AI in Cloud Computing",
    "AI in DevOps",
    "AI in Agile Development",
    "AI in Software Architecture",
    "AI in Version Control",
    "Application Development",
    "Flutter Development",
    "Mobile App Development",
    "Mobile Applications",
    "Cross-Platform Development",
    "Mobile Development",
    "Mobile UI/UX",
    "Mobile Software Development",
    "Mobile Solutions",
    "Mobile Technologies",
    "Mobile Software Engineer",
    "Mobile Developer",
    "React Native Development",
    "Mobile Web Development",
    "Mobile Web Applications",
    "Mobile Web Design",
    "Mobile Web Technologies",
    "Mobile Web Solutions",
    "Mobile Web Developer",
    "Mobile Web Software Engineer",
    "Mobile Development Portfolio",
    "Mobile Development Projects",
    "Mobile Development Solutions",
    "Mobile Development Technologies",
    "Mobile Development Innovations",
    "Mobile Development Trends",
    "Mobile Development Best Practices",
    "Mobile Development Techniques",
    "Mobile Development Tools",
    "Mobile Development Frameworks",
    "Mobile Development Libraries",
    "Mobile Development Languages",
    "Mobile Development Platforms",
    "Mobile Development Ecosystem",
    "Mobile Development Community",
    "Mobile Development Resources",
    "Mobile Development Blogs",
    "Mobile Development Tutorials",
    "Mobile Development Courses",
    "Mobile Development Workshops",
    "Mobile Development Conferences",
    "Mobile Development Meetups",
    "Mobile Development Events",
    "Mobile Development News",
    "Mobile Development Updates",
    "Mobile Development Insights",
    "Mobile Development Tips",
    "Mobile Development Tricks",
    "Mobile Development Hacks",
    "Mobile Development Guides"
  ],
  authors: [{ name: "Utkarsh Deoli" }],
  creator: "Utkarsh Deoli",
  publisher: "Utkarsh Deoli",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://utkarshdeoli.in",
    title: "Utkarsh Deoli | Developer Portfolio",
    description: "Portfolio of Utkarsh Deoli, a Developer specializing in modern web technologies.",
    siteName: "Utkarsh Deoli Portfolio",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Utkarsh Deoli - Developer Portfolio",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Utkarsh Deoli | Developer Portfolio",
    description: "Portfolio of Utkarsh Deoli, a Developer specializing in modern web technologies.",
    creator: "@utkarshdeoli",
    images: ["/og-image.png"],
  },
  verification: {
    google: "google-site-verification-code",
  },
  category: "technology"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}